---
# Source: oes/charts/prometheus/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: isd
    chart: prometheus-11.16.2
    heritage: Helm
  name: isd-prometheus-alertmanager
  namespace: isdtest2406
  annotations:
    {}
