---
# Source: oes/templates/services/oes-auditservice-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: auditservice
    heritage: "Helm"
    release: "isd"
    chart: "oes-4.0.52"
  name: oes-audit-service
spec:
  ports:
  - name: auditservice
    port: 8097
    protocol: TCP
    targetPort: 8097
  - name: opentelemetry
    protocol: TCP
    port: 19090
    targetPort: 19090
  selector:
    app: oes
    component: auditservice
  type: ClusterIP
