---
# Source: oes/charts/prometheus/templates/node-exporter/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: isd
    chart: prometheus-11.16.2
    heritage: Helm
  name: isd-prometheus-node-exporter
  namespace: isdtest2406
  annotations:
    {}
