---
# Source: oes/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: isd-grafana
  namespace: isdtest2406
  labels:
    helm.sh/chart: grafana-7.0.19
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: isd
    app.kubernetes.io/version: "10.2.2"
    app.kubernetes.io/managed-by: Helm
data:
  
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    allow_embedding = true
    [server]
    domain = isdtest2406.qabox.opsmx.org
    root_url = https://isdtest2406.qabox.opsmx.org/grafana
    serve_from_sub_path = true
