---
# Source: oes/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isd-grafana
  namespace: isdtest2406
  labels:
    helm.sh/chart: grafana-7.0.19
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: isd
    app.kubernetes.io/version: "10.2.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: isd-grafana
subjects:
- kind: ServiceAccount
  name: isd-grafana
  namespace: isdtest2406
