---
# Source: oes/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isd-grafana
  namespace: isdtest2406
  labels:
    helm.sh/chart: grafana-7.0.19
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: isd
    app.kubernetes.io/version: "10.2.2"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  
  admin-user: "YWRtaW4="
  admin-password: "b3BzbXhhZG1pbjEyMw=="
  ldap-toml: ""
