---
# Source: oes/charts/prometheus/templates/server/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: "server"
    app: prometheus
    release: isd
    chart: prometheus-11.16.2
    heritage: Helm
  name: isd-prometheus-server
  namespace: isdtest2406
spec:
  selector:
    matchLabels:
      component: "server"
      app: prometheus
      release: isd
  replicas: 1
  template:
    metadata:
      labels:
        component: "server"
        app: prometheus
        release: isd
        chart: prometheus-11.16.2
        heritage: Helm
    spec:
      serviceAccountName: isd-prometheus-server
      containers:
        - name: prometheus-server-configmap-reload
          image: "jimmidyson/configmap-reload:v0.4.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://127.0.0.1:9090/-/reload
            - --volume-dir=/etc/alerts.d
          resources:
            {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: configmap-reload-spinnaker-alerts
              mountPath: /etc/alerts.d
              subPath: 
              readOnly: true

        - name: prometheus-server
          image: "prom/prometheus:v2.21.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --storage.tsdb.retention.time=15d
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: storage-volume
              mountPath: /data
              subPath: ""
            - name: server-spinnaker-alerts
              mountPath: /etc/alerts.d
              subPath: 
              readOnly: true
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: isd-prometheus-server
        - name: storage-volume
          persistentVolumeClaim:
            claimName: isd-prometheus-server
        - name: configmap-reload-spinnaker-alerts
          configMap:
            name: spinnaker-alerts
        - name: server-spinnaker-alerts
          configMap:
            name: spinnaker-alerts
        - name: spinnaker-alerts
          configMap:
            name: spinnaker-alerts
