---
# Source: oes/charts/prometheus/templates/server/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: prometheus
    release: isd
    chart: prometheus-11.16.2
    heritage: Helm
  name: isd-prometheus-server
  namespace: isdtest2406
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
